#!/bin/sh

if [ -n "$1" ]; then
  PROF_FILE=$(realpath "$1")
  PROF_NAME=$(basename "$PROF_FILE")
fi

if [ -n "$PROF_FILE" -a -n "$PROF_NAME" ]; then
  docker run --rm -it -v "$PROF_FILE:/home/viewprof/$PROF_NAME" viewprof "/home/viewprof/$PROF_NAME"
else 
  docker run --rm -it viewprof
fi
